### ISSUE TITLE
non-zero return xdg-open causes shfm to exit

### ISSUE THREAD

**Issue by bkauler** [dylanaraps/shfm#15] opened 2020-08-07 14:26 UTC
I am using the environment variable to run external /sbin/xdg-open which is a custom script in the initramfs, to perform basic mime handling.

I had it returning non-zero if failed to find an appropriate app to run the file. However, this causes shfm to exit.

shfm should do nothing if receive a non-zero return from xdg-open. 

That is standard behaviour of xdg-open, as defined in its man page, and I think nnn also reads the return value.

**Comment by dylanaraps** [comment] 2020-08-07 15:10
Which shell are you using (what is `/bin/sh`?)? I cannot reproduce this at all. The opener script should not cause exit as `|| :` is used (ignore non-zero exit code). Is this with the latest master?

**Comment by dylanaraps** [comment] 2020-08-07 15:15
I cannot reproduce this with `ash`, `dash` and `bash` (as `/bin/sh`) while using an opener script that exits with `1`.

**Comment by bkauler** [comment] 2020-08-08 01:07
Sorry, my mistake, I had an old version in the initramfs.

Your latest works great, except in the initramfs when first tried to run it:

/bin/shfm: 413: Can't create /dev/tty: no such file or directory

/dev/tty device node is present. Anyway, I removed that ">/dev/tty" from the last line and it worked.

Real nice, I will do a write-up on my blog! And shfm will be in the initramfs of next release of EasyOS.

**Comment by bkauler** [comment] 2020-08-08 01:08
Sorry, my mistake, I had an old version in the initramfs.

Your latest works great, except in the initramfs when first tried to run it:

/bin/shfm: 413: Can't create /dev/tty: no such file or directory

/dev/tty device node is present. Anyway, I removed that ">/dev/tty" from the last line and it worked.

Real nice, I will do a write-up on my blog! And shfm will be in the initramfs of next release of EasyOS.

**Comment by dylanaraps** [comment] 2020-08-08 07:09
> /bin/shfm: 413: Can't create /dev/tty: no such file or directory
> /dev/tty device node is present. 

Do you have write permissions to this device file?

POSIX states:

```
The following files shall exist on conforming systems and shall be both readable and writable:

/dev/tty
    In each process, a synonym for the controlling terminal associated with the process group of that process, if any. 
    It is useful for programs or shell procedures that wish to be sure of writing messages to or reading data from the 
    terminal no matter how output has been redirected. It can also be used for applications that demand the name of 
    a file for output, when typed output is desired and it is tiresome to find out what terminal is currently in use. 
```

> Real nice, I will do a write-up on my blog! And shfm will be in the initramfs of next release of EasyOS.

Awesome!

**Comment by dylanaraps** [comment] 2020-08-08 07:14
Closing this as the main issue has been resolved. :+1:

**Closed as completed by dylanaraps** 2020-08-08 07:14 UTC

**Comment by bkauler** [comment] 2020-08-09 03:51
In the initramfs, at least for the simple busybox-based one, /dev/tty does not work, there is only /dev/console.

I found a fix, posted about in my blog post:

https://bkhome.org/news/202008/fix-for-devtty-in-initrd.html

Where I have "/bin/sh" in the init script, to dropout to a shell, replaced with "setsid cttyhack sh".
